import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{readFile}from'node:fs/promises';import{Pool}from'pg';
test('confidence survey in disposable PostgreSQL',{skip:!process.env.MLG_TEST_DATABASE_URL},async t=>{
 const root=new Pool({connectionString:process.env.MLG_TEST_DATABASE_URL}),name='mlg_survey_'+randomUUID().replaceAll('-','');await root.query('create database '+name);const url=new URL(process.env.MLG_TEST_DATABASE_URL!);url.pathname='/'+name;const db=new Pool({connectionString:url.toString()});
 try{
 for(const f of['mlg-window-integrity-base.sql','mlg-window-resilience-base.sql','mlg-window-ledger.sql','mlg-window-integrity.sql','mlg-window-corrected-quotas.sql','mlg-window-overdraft.sql','mlg-window-trust-base.sql','mlg-window-trust-and-signals.sql','mlg-effective-quota-notices.sql','mlg-confidence-survey.sql','mlg-confidence-capacity.sql'])await db.query(await readFile(new URL('./fixtures/'+f,import.meta.url),'utf8'));
 await db.query('alter table public.negotiations add column created_at timestamptz default now()');
 const actor=randomUUID(),cycle=randomUUID();await db.query('insert into auth.users(id) values($1)',[actor]);await db.query('insert into public.admin_users values($1)',[actor]);await db.query("select set_config('mlg_test.actor',$1,false)",[actor]);await db.query('insert into public.market_windows(market_cycle_id,transfer_window_open,trade_window_open) values($1,false,false)',[cycle]);
 const value=async(sql:string,args:any[]=[])=>Object.values((await db.query(sql,args)).rows[0])[0] as any;
 await t.test('refuses incomplete directory',async()=>{await assert.rejects(()=>value('select public.admin_start_market_confidence_survey($1)',[cycle]),/25 técnicos/);});
 const clubs:string[]=[];for(let i=0;i<25;i++){const id=randomUUID();clubs.push(id);await db.query('insert into public.clubs(id,name,balance) values($1,$2,100)',[id,'Club '+i]);await db.query('insert into public.whatsapp_market_club_directory values($1,$2,$3)',[id,'Coach '+i,'55110000000'+String(i).padStart(2,'0')]);}
 let survey:string;
 await t.test('queues 25 once and binds to upcoming window',async()=>{const r=await value('select public.admin_start_market_confidence_survey($1)',[cycle]);survey=r.id;assert.equal(r.queued,25);assert.equal((await value('select public.admin_start_market_confidence_survey($1)',[cycle])).duplicate,true);assert.equal(Number(await value('select count(*) from private.market_confidence_deliveries')),25);assert.equal(await value('select market_cycle_id from public.market_confidence_surveys'),null);});
 const payload=(i:number,text:string)=>({aliases:['55110000000'+String(i).padStart(2,'0')+'@s.whatsapp.net'],text,messageId:'reply-'+i,groups:['12345@g.us']});
 await t.test('ignores unsolicited yes before delivery and unknown identities',async()=>{assert.equal((await value("select private.market_confidence_bot('survey_answer',$1)",[payload(0,'sim')])).matched,false);assert.equal((await value("select private.market_confidence_bot('survey_answer',$1)",[{...payload(0,'sim'),aliases:['999@s.whatsapp.net']}])).matched,false);});
 await t.test('leases independently and retries failed sends',async()=>{const r=await value("select private.market_confidence_bot('survey_claim','{}')");assert.equal(r.notices.length,10);const n=r.notices[0];await value("select private.market_confidence_bot('survey_ack',$1)",[{...n,sent:false}]);assert.equal(Number(await value('select count(*) from private.market_confidence_deliveries where delivered_at is not null')),0);await db.query("update private.market_confidence_deliveries set delivered_at=now(),lease_id=null,lease_until=null where kind='question'");});
 await t.test('persists yes and no, forwards each once, prevents reply replay',async()=>{await value("select private.market_confidence_bot('survey_answer',$1)",[payload(0,'SIM')]);await value("select private.market_confidence_bot('survey_answer',$1)",[payload(1,'não')]);assert.equal((await value("select private.market_confidence_bot('survey_answer',$1)",[payload(0,'não')])).duplicate,true);assert.equal(await value('select answer from public.market_confidence_answers where club_id=$1',[clubs[0]]),true);assert.equal(await value('select answer from public.market_confidence_answers where club_id=$1',[clubs[1]]),false);assert.equal(Number(await value("select count(*) from private.market_confidence_deliveries where kind='answer'")),2);});
 await t.test('opens with the chosen effective limits, leaves other clubs unchanged',async()=>{const next=randomUUID();await db.query('update public.market_windows set market_cycle_id=$1,transfer_window_open=true',[next]);assert.equal(await value('select market_cycle_id from public.market_confidence_surveys'),next);const yes=await value('select private.market_effective_limits($1,$2)',[clubs[0],next]),no=await value('select private.market_effective_limits($1,$2)',[clubs[1],next]);assert.equal(yes.purchase_limit,5);assert.equal(yes.trade_limit,1);assert.equal(no.purchase_limit,4);assert.equal(no.trade_limit,2);});
 await t.test('conversion never consumes a trade already completed or reserved',async()=>{const current=await value('select market_cycle_id from public.market_windows');for(let i=0;i<2;i++)await db.query("insert into public.negotiations(id,type,club_a_id,club_b_id,status,market_cycle_id) values($1,'trade',$2,$3,'executed',$4)",[randomUUID(),clubs[2],clubs[3],current]);await value("select private.market_confidence_bot('survey_answer',$1)",[payload(2,'sim')]);assert.equal(await value('select answer from public.market_confidence_answers where club_id=$1',[clubs[2]]),true);assert.equal(await value('select quota_applied from public.market_confidence_answers where club_id=$1',[clubs[2]]),false);const limits=await value('select private.market_effective_limits($1,$2)',[clubs[2],current]);assert.equal(limits.purchase_limit,4);assert.equal(limits.trade_limit,2);});
 await t.test('closing preserves answers and backup; next survey is separate',async()=>{const current=await value('select market_cycle_id from public.market_windows');for(const status of ['approved','rejected'])await db.query('insert into public.transfers(id,to_club_id,status,market_cycle_id,price) values($1,$2,$3,$4,0)',[randomUUID(),clubs[4],status,current]);const player=randomUUID(),contract=randomUUID();await db.query("insert into public.players(id,club_id,name) values($1,$2,'Backup player')",[player,clubs[4]]);await db.query("insert into public.negotiations(id,type,club_a_id,club_b_id,player_ids_b,status,market_cycle_id) values($1,'trade',$2,$3,$4,'executed',$5)",[contract,clubs[4],clubs[5],JSON.stringify([player]),current]);for(const status of ['settled','rejected'])await db.query("insert into public.whatsapp_market_inbox(id,kind,status,participant_id,parsed,market_cycle_id,negotiation_id,to_club_id,from_club_id,player_ids_from,player_ids_to,amount) values($1,'trade',$2,'5511000000004@s.whatsapp.net','{}',$3,$4,$5,$6,$7,'{}',0)",[randomUUID(),status,current,contract,clubs[4],clubs[5],[player]]);await db.query('update public.market_windows set transfer_window_open=false');assert.equal(await value('select active from public.market_confidence_surveys'),false);const backup=await value('select public.admin_get_market_window_backup($1)',[current]);assert.equal(backup.confidence_answers.length,25);assert.equal(backup.confidence_answers.filter((a:any)=>a.answer!==null).length,3);assert.deepEqual(backup.proposals.map((p:any)=>p.status).sort(),['rejected','settled']);assert.deepEqual(backup.transfers.map((p:any)=>p.status).sort(),['approved','rejected']);assert.equal(Number(await value('select balance from public.clubs where id=$1',[clubs[0]])),100);const r=await value('select public.admin_start_market_confidence_survey($1)',[current]);assert.notEqual(r.id,survey);assert.equal(r.queued,25);});
 await t.test('anonymous and members cannot start or read backup',async()=>{assert.equal(await value("select has_function_privilege('anon','public.admin_start_market_confidence_survey(uuid)','execute')"),false);assert.equal(await value("select has_table_privilege('authenticated','public.market_confidence_answers','update')"),false);await db.query("select set_config('mlg_test.actor','',false)");await assert.rejects(()=>value('select public.admin_get_market_window_backup($1)',[cycle]),/Somente ADMs/);});
 }finally{await db.end();await root.query('drop database '+name);await root.end();}
});
