import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {Pool,type PoolClient} from 'pg';

test('market safety and concurrency in disposable PostgreSQL',{skip:!process.env.MLG_TEST_DATABASE_URL},async t=>{
 const admin=new Pool({connectionString:process.env.MLG_TEST_DATABASE_URL}),name='mlg_safety_test_'+randomUUID().replaceAll('-','');
 await admin.query('create database '+name);const url=new URL(process.env.MLG_TEST_DATABASE_URL!);url.pathname='/'+name;const db=new Pool({connectionString:url.toString()});
 try{
  for(const file of ['mlg-window-integrity-base.sql','mlg-window-resilience-base.sql','mlg-window-resilience-contracts.sql','mlg-window-ledger.sql','mlg-window-integrity.sql','mlg-window-corrected-quotas.sql','mlg-window-reconcile.sql','mlg-window-resilience.sql','mlg-window-health.sql','mlg-window-safety-bridge.sql'])await db.query(await readFile(new URL('./fixtures/'+file,import.meta.url),'utf8'));
  const actor=randomUUID(),cycle=randomUUID();await db.query('insert into auth.users values($1)',[actor]);await db.query('insert into public.admin_users values($1)',[actor]);await db.query('insert into public.market_windows(market_cycle_id) values($1)',[cycle]);await db.query('insert into public.platform_member_access values(true,true)');
  const client=await db.connect();await client.query("select set_config('mlg_test.actor',$1,false)",[actor]);
  async function scalar(sql:string,args:any[]=[],c=client){const r=await c.query(sql,args),v=Object.values(r.rows[0])[0] as any;return r.fields[0]?.dataTypeID===20?Number(v):v;}
  async function seed(){const buyer=randomUUID(),seller=randomUUID(),p=randomUUID(),p2=randomUUID();await client.query("insert into public.clubs(id,name,balance) values($1,'Buyer',100),($2,'Seller',0)",[buyer,seller]);await client.query("insert into public.players(id,club_id,name) values($1,$3,'One'),($2,$3,'Two')",[p,p2,seller]);return {buyer,seller,p,p2};}
  async function prepare(s:Awaited<ReturnType<typeof seed>>,amount=20,p=s.p,c=client){const source=randomUUID(),inbox=randomUUID();await c.query("insert into public.negotiations(id,type,club_a_id,club_b_id,player_ids_b,cash_from_a,status,market_cycle_id) values($1,'transfer',$2,$3,$4,$5,'open',$6)",[source,s.buyer,s.seller,JSON.stringify([p]),amount,cycle]);await c.query("insert into public.whatsapp_market_inbox(id,status,kind,negotiation_id,from_club_id,to_club_id,amount,player_ids_from,market_cycle_id) values($1,'awaiting_signatures','transfer',$2,$3,$4,$5,$6,$7)",[inbox,source,s.seller,s.buyer,amount,[p],cycle]);return {source,inbox};}
  const pids=new WeakMap<PoolClient,number>();
  async function twoClients(fn:(a:PoolClient,b:PoolClient)=>Promise<void>){const a=await db.connect(),b=await db.connect();try{for(const c of [a,b]){pids.set(c,(await c.query('select pg_backend_pid() as pid')).rows[0].pid);await c.query('begin');await c.query("select set_config('mlg_test.actor',$1,true)",[actor]);await c.query("set local statement_timeout='10s'");}await fn(a,b);}finally{for(const c of [a,b]){await c.query('rollback');c.release();}}}
  async function waiting(c:PoolClient){const pid=pids.get(c);for(let i=0;i<100;i++){const r=await db.query("select wait_event_type from pg_stat_activity where pid=$1",[pid]);if(r.rows[0]?.wait_event_type==='Lock')return;await new Promise(r=>setTimeout(r,10));}throw Error('Concurrent transaction did not wait on a lock');}

  await t.test('two ADMs approving the same proposal produce one debit, one credit and one roster movement',async()=>{
   const s=await seed(),r=await prepare(s),preview=await scalar('select public.admin_preview_whatsapp_market_approval($1,1)',[r.inbox]);
   await twoClients(async(a,b)=>{const first=await scalar('select public.admin_approve_whatsapp_market_with_preview($1,1,$2)',[r.inbox,preview.preview_hash],a);assert.equal(first.success,true);const second=scalar('select public.admin_approve_whatsapp_market_with_preview($1,1,$2)',[r.inbox,preview.preview_hash],b);await waiting(b);await a.query('commit');assert.equal((await second).duplicate,true);await b.query('commit');});
   assert.equal(await scalar('select balance from public.clubs where id=$1',[s.buyer]),80);assert.equal(await scalar('select balance from public.clubs where id=$1',[s.seller]),20);assert.equal(await scalar('select count(*) from public.transactions where club_id in($1,$2)',[s.buyer,s.seller]),2);assert.equal(await scalar('select club_id from public.players where id=$1',[s.p]),s.buyer);assert.equal(await scalar('select count(*) from private.whatsapp_market_asset_reservations where source_id=$1',[r.source]),0);
  });
  await t.test('same player cannot be reserved by concurrent proposals; cancellation releases it',async()=>{
   const s=await seed();let first:any;
   await twoClients(async(a,b)=>{first=await prepare(s,20,s.p,a);const second=prepare(s,20,s.p,b).then(()=>({ok:true}),error=>({ok:false,error}));await waiting(b);await a.query('commit');const result=await second;assert.equal(result.ok,false);assert.match(String((result as any).error),/reservado/);});
   await client.query("update public.negotiations set status='cancelled' where id=$1",[first.source]);await prepare(s,20,s.p);
  });
  await t.test('concurrent different-player proposals cannot reserve more than the club balance',async()=>{
   const s=await seed();await twoClients(async(a,b)=>{await prepare(s,70,s.p,a);const second=prepare(s,50,s.p2,b).then(()=>({ok:true}),error=>({ok:false,error}));await waiting(b);await a.query('commit');const result=await second;assert.equal(result.ok,false);assert.match(String((result as any).error),/Saldo disponível insuficiente/);});assert.equal(await scalar('select private.market_other_commitment($1)',[s.buyer]),70);
  });
  await t.test('external own reservation is excluded from preview and duplicate free agent is blocked',async()=>{
   const s=await seed(),agent=randomUUID(),transfer=randomUUID(),inbox=randomUUID();await client.query("insert into public.free_agents(id,name,market_value,status) values($1,'External',70,'available')",[agent]);await client.query("insert into public.transfers(id,free_agent_id,to_club_id,price,status,market_cycle_id) values($1,$2,$3,70,'pending',$4)",[transfer,agent,s.buyer,cycle]);await client.query("insert into public.whatsapp_market_inbox(id,status,kind,transfer_id,to_club_id,free_agent_id,amount,market_cycle_id) values($1,'awaiting_signatures','transfer',$2,$3,$4,70,$5)",[inbox,transfer,s.buyer,agent,cycle]);const p=await scalar('select public.admin_preview_whatsapp_market_approval($1,1)',[inbox]);assert.equal(p.clubs[0].available,100);assert.equal(p.clubs[0].after,30);await assert.rejects(()=>client.query("insert into public.transfers(id,free_agent_id,to_club_id,price,status,market_cycle_id) values($1,$2,$3,20,'pending',$4)",[randomUUID(),agent,s.buyer,cycle]),/reservado/);
  });
  await t.test('pause is durable, requires ADM, blocks execution and resume invalidates an old approval preview',async()=>{
   const s=await seed(),r=await prepare(s),p=await scalar('select public.admin_preview_whatsapp_market_approval($1,1)',[r.inbox]);const v=await scalar('select public.admin_set_whatsapp_market_pause(true,1,$1)',['Pause after ADM inspection']);assert.equal(v.paused,true);await assert.rejects(()=>scalar('select public.admin_approve_whatsapp_market_with_preview($1,1,$2)',[r.inbox,p.preview_hash]),/pausadas/);assert.equal(await scalar('select count(*) from public.transactions where club_id=$1',[s.buyer]),0);await assert.rejects(()=>scalar('select public.admin_set_whatsapp_market_pause(false,1,$1)',['Resume after ADM inspection']),/Outro ADM/);await scalar('select public.admin_set_whatsapp_market_pause(false,2,$1)',['Resume after ADM inspection']);await assert.rejects(()=>scalar('select public.admin_approve_whatsapp_market_with_preview($1,1,$2)',[r.inbox,p.preview_hash]),/novo resumo/);await client.query("select set_config('mlg_test.actor','',false)");await assert.rejects(()=>scalar('select public.admin_set_whatsapp_market_pause(true,3,$1)',['Unauthorized emergency pause']),/Somente ADMs/);await client.query("select set_config('mlg_test.actor',$1,false)",[actor]);
  });
  await t.test('pause waits for already-started financial operation and cannot roll back its completed result',async()=>{
   const s=await seed(),r=await prepare(s),p=await scalar('select public.admin_preview_whatsapp_market_approval($1,1)',[r.inbox]);await twoClients(async(a,b)=>{await scalar('select public.admin_approve_whatsapp_market_with_preview($1,1,$2)',[r.inbox,p.preview_hash],a);const pause=scalar('select public.admin_set_whatsapp_market_pause(true,3,$1)',['Pause while operation completes'],b);await waiting(b);await a.query('commit');assert.equal((await pause).paused,true);await b.query('commit');});assert.equal(await scalar('select balance from public.clubs where id=$1',[s.buyer]),80);await scalar('select public.admin_set_whatsapp_market_pause(false,4,$1)',['Resume after operation completed']);
  });
  await t.test('repeated ingestion after a lost acknowledgement produces one inbox record',async()=>{
   const token='a'.repeat(64),group='12345@g.us',message='REPLAY-'+randomUUID();await client.query("insert into private.whatsapp_market_credentials values(encode(sha256(convert_to($1,'UTF8')),'hex'))",[token]);await client.query("insert into public.whatsapp_market_channels values($1,'transfer')",[group]);const payload={group,messageId:message,participant:'551191234567@s.whatsapp.net',text:'Fixture proposal',parsed:{kind:'transfer',issues:[]}};const first=await scalar('select public.bot_whatsapp_market_gate($1,$2,$3)',[token,'ingest',payload]);const second=await scalar('select public.bot_whatsapp_market_gate($1,$2,$3)',[token,'ingest',payload]);assert.equal(second.id,first.id);assert.equal(second.duplicate,true);assert.equal(await scalar('select count(*) from public.whatsapp_market_inbox where message_id=$1',[message]),1);
  });
  await t.test('health outage emits one incident and recovery is queued for ADM WhatsApp; delivery leases survive retry',async()=>{
   const payload={phase:'CONNECTED',enabled:true,healthy:true,blocked:false,groups:['98765@g.us'],proposalQueue:0,responseQueue:0,oldestAgeSeconds:0};await scalar('select private.receive_whatsapp_market_health($1)',[payload]);await client.query("update public.whatsapp_market_health set last_heartbeat=clock_timestamp()-interval '5 minutes',bad_since=clock_timestamp()-interval '5 minutes'");await client.query('select private.check_whatsapp_market_health()');await client.query('select private.check_whatsapp_market_health()');assert.equal(await scalar('select count(*) from public.whatsapp_market_health_incidents'),1);await scalar('select private.receive_whatsapp_market_health($1)',[payload]);assert.equal(await scalar('select count(*) from public.whatsapp_market_health_incidents where resolved_at is not null'),1);const first=await scalar('select private.claim_whatsapp_market_health_notices($1)',[JSON.stringify(payload.groups)]);assert.equal(first.notices.length,2);assert.equal((await scalar('select private.claim_whatsapp_market_health_notices($1)',[JSON.stringify(payload.groups)])).notices.length,0);await client.query("update private.whatsapp_market_health_deliveries set lease_until=clock_timestamp()-interval '1 second'");const retry=await scalar('select private.claim_whatsapp_market_health_notices($1)',[JSON.stringify(payload.groups)]);assert.equal(retry.notices.length,2);const stale=await scalar('select public.bot_whatsapp_market_gate($1,$2,$3)',['a'.repeat(64),'ack_health',{id:first.notices[0].id,lease:first.notices[0].lease,sent:true}]);assert.equal(stale.success,false);assert.equal(await scalar('select count(*) from private.whatsapp_market_health_deliveries where delivered_at is not null'),0);
  });
  await t.test('intentional batch waiting does not create queue alert and a duplicate financial effect is rejected',async()=>{
   await scalar('select private.receive_whatsapp_market_health($1)',[{phase:'CONNECTED',enabled:true,healthy:true,blocked:true,groups:[],proposalQueue:12,responseQueue:0,oldestAgeSeconds:700}]);assert.equal(await scalar("select status from public.whatsapp_market_health where id"),'healthy');const s=await seed(),id=randomUUID();await client.query("insert into public.transactions(club_id,type,amount,description) values($1,'negotiation_receipt',5,$2)",[s.buyer,'Recebimento da negociação '+id]);await assert.rejects(()=>client.query("insert into public.transactions(club_id,type,amount,description) values($1,'negotiation_receipt',5,$2)",[s.buyer,'Recebimento da negociação '+id]),/market_financial_effect_once/);assert.equal(await scalar('select balance from public.clubs where id=$1',[s.buyer]),105);
  });
  client.release();
 }finally{await db.end();await admin.query('drop database '+name);await admin.end();}
});
