import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';import {Pool} from 'pg';
test('Market integrity SQL in a disposable PostgreSQL database',{skip:!process.env.MLG_TEST_DATABASE_URL},async t=>{
 const url=process.env.MLG_TEST_DATABASE_URL!,admin=new Pool({connectionString:url}),dbname='mlg_integrity_test_'+randomUUID().replaceAll('-','');await admin.query('create database '+dbname);const target=new URL(url);target.pathname='/'+dbname;const db=new Pool({connectionString:target.toString()});
 try{
  for(const file of ['mlg-window-integrity-base.sql','mlg-window-ledger.sql','mlg-window-integrity.sql','mlg-window-corrected-quotas.sql','mlg-window-reconcile.sql'])await db.query(await readFile(new URL('./fixtures/'+file,import.meta.url),'utf8'));
  const client=await db.connect(),actor=randomUUID();await client.query('insert into auth.users values($1);',[actor]);await client.query('insert into public.admin_users values($1)',[actor]);
  const scalar=async(sql:string,args:any[]=[])=>Object.values((await client.query(sql,args)).rows[0])[0] as any;
  const negative=async(fn:()=>Promise<any>,pattern:RegExp)=>{await client.query('savepoint negative');try{await assert.rejects(fn,pattern);}finally{await client.query('rollback to savepoint negative');await client.query('release savepoint negative');}};
  async function scenario(kind='transfer',external=false,settle=true){
   const buyer=randomUUID(),seller=randomUUID(),p=randomUUID(),p2=randomUUID(),source=randomUUID(),inbox=randomUUID(),cycle=randomUUID(),agent=randomUUID();
   await client.query('insert into public.market_windows(market_cycle_id) values($1)',[cycle]);await client.query('insert into public.platform_member_access values(true,false)');
   await client.query("insert into public.clubs(id,name,balance) values($1,'Buying Club',100),($2,'Selling Club',0)",[buyer,seller]);
   await client.query("insert into public.players(id,club_id,name) values($1,$2,'Player One')",[p,external?buyer:seller]);
   if(kind==='trade')await client.query("insert into public.players(id,club_id,name) values($1,$2,'Player Two')",[p2,buyer]);
   const amount=kind==='trade'?0:20;
   if(external){await client.query("insert into public.free_agents(id,name,week_rating,market_value,status,acquired_by_club_id) values($1,'External Player','A',20,'acquired',$2)",[agent,buyer]);await client.query("insert into public.transfers(id,player_id,to_club_id,free_agent_id,price,status,market_cycle_id) values($1,$2,$3,$4,20,'approved',$5)",[source,p,buyer,agent,cycle]);}
   else await client.query("insert into public.negotiations(id,type,club_a_id,club_b_id,player_ids_a,player_ids_b,cash_from_a,status,market_cycle_id) values($1,$2,$3,$4,$5,$6,$7,'open',$8)",[source,kind,buyer,seller,JSON.stringify(kind==='trade'?[p2]:[]),JSON.stringify([p]),amount,cycle]);
   await client.query("insert into public.whatsapp_market_inbox(id,status,kind,transfer_id,negotiation_id,from_club_id,to_club_id,free_agent_id,amount,player_ids_from,player_ids_to,market_cycle_id) values($1,'awaiting_signatures',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",[inbox,kind,external?source:null,external?null:source,external?null:seller,buyer,external?agent:null,amount,external?[]:[p],kind==='trade'?[p2]:[],cycle]);
   if(settle){if(!external){await client.query('update public.players set club_id=$1 where id=$2',[buyer,p]);if(kind==='trade')await client.query('update public.players set club_id=$1 where id=$2',[seller,p2]);await client.query("update public.negotiations set status='executed' where id=$1",[source]);}
    if(amount){await client.query('insert into public.transactions(club_id,type,amount,description) values($1,$2,-20,$3)',[buyer,external?'external_transfer_purchase':'negotiation_payment',external?'Contratação assinada '+source:'Pagamento da negociação '+source]);if(!external)await client.query("insert into public.transactions(club_id,type,amount,description) values($1,'negotiation_receipt',20,$2)",[seller,'Recebimento da negociação '+source]);}
    await client.query("update public.whatsapp_market_inbox set status='settled',settled_at=clock_timestamp() where id=$1",[inbox]);
   }
   return {buyer,seller,p,p2,source,inbox,cycle,agent};
  }
  const correct=async(s:any,confirm=false,hash:string|null=null,request=randomUUID())=>scalar('select public.admin_correct_whatsapp_market_settlement($1,$2,$3,$4,$5)',[s.inbox,request,'Correction after ADM review',confirm,hash]);
  async function run(name:string,fn:()=>Promise<void>){await t.test(name,async()=>{await client.query('begin');await client.query("select set_config('mlg_test.actor',$1,true)",[actor]);try{await fn();}finally{await client.query('rollback');}});}
  await run('internal correction restores money, roster and quotas once; original ledger remains immutable',async()=>{const s=await scenario();assert.equal((await scalar('select private.market_window_usage($1,$2)',[s.buyer,s.cycle])).purchases,1);const preview=await correct(s);assert.equal(await scalar('select count(*) from public.transactions'),2);const request=randomUUID(),r=await correct(s,true,preview.preview_hash,request);assert.equal(r.confirmed,true);assert.equal(await scalar('select balance from public.clubs where id=$1',[s.buyer]),100);assert.equal(await scalar('select balance from public.clubs where id=$1',[s.seller]),0);assert.equal(await scalar('select club_id from public.players where id=$1',[s.p]),s.seller);assert.equal((await scalar('select private.market_window_usage($1,$2)',[s.buyer,s.cycle])).purchases,0);assert.equal((await correct(s,true,preview.preview_hash,request)).duplicate,true);assert.equal(await scalar('select count(*) from public.transactions'),4);assert.equal(await scalar('select count(*) from public.whatsapp_market_corrections'),1);await negative(()=>client.query('update public.transactions set amount=999'),/imutável/);await negative(()=>client.query('delete from public.whatsapp_market_corrections'),/imutável/);assert.equal(await scalar("select count(*) from public.audit_logs where action='whatsapp_market_settlement_corrected'"),1);});
  await run('ownership changes and subsequent pending deals block correction',async()=>{const s=await scenario();await client.query('update public.players set name=$1 where id=$2',['Edited Player',s.p]);await negative(()=>correct(s),/jogador ou elenco mudou/);assert.equal(await scalar('select count(*) from public.whatsapp_market_corrections'),0);});
  await run('seller balance and active commitments prevent unsafe refunds',async()=>{const s=await scenario();await client.query('insert into public.test_commitments values($1,15)',[s.seller]);await negative(()=>correct(s),/Saldo disponível insuficiente/);assert.equal(await scalar('select count(*) from public.transactions'),2);});
  await run('stale correction previews cannot move cash or players',async()=>{const s=await scenario(),p=await correct(s);await client.query("insert into public.transactions(club_id,type,amount,description) values($1,'adjustment',1,'New credit')",[s.buyer]);await negative(()=>correct(s,true,p.preview_hash),/nova prévia/);assert.equal(await scalar('select count(*) from public.whatsapp_market_corrections'),0);});
  await run('external correction refunds purchase, archives created player and releases free agent',async()=>{const s=await scenario('transfer',true),p=await correct(s);await correct(s,true,p.preview_hash);assert.equal(await scalar('select balance from public.clubs where id=$1',[s.buyer]),100);assert.equal(await scalar('select roster_active from public.players where id=$1',[s.p]),false);assert.equal(await scalar('select status from public.free_agents where id=$1',[s.agent]),'available');assert.equal(await scalar('select count(*) from public.players'),1);assert.equal((await scalar('select private.market_window_usage($1,$2)',[s.buyer,s.cycle])).purchases,0);});
  await run('trade reversal returns both players, releases quota and creates no financial fiction',async()=>{const s=await scenario('trade'),p=await correct(s);await correct(s,true,p.preview_hash);assert.equal(await scalar('select club_id from public.players where id=$1',[s.p]),s.seller);assert.equal(await scalar('select club_id from public.players where id=$1',[s.p2]),s.buyer);assert.equal(await scalar('select count(*) from public.transactions'),0);assert.equal((await scalar('select private.market_window_usage($1,$2)',[s.buyer,s.cycle])).trades,0);});
  await run('approval summary binds current financial state and rejects stale approval',async()=>{const s=await scenario('transfer',false,false),p=await scalar('select public.admin_preview_whatsapp_market_approval($1,1)',[s.inbox]);assert.equal(p.clubs.find((c:any)=>c.id===s.buyer).after,80);await client.query('update public.clubs set balance=101 where id=$1',[s.buyer]);await negative(()=>scalar('select public.admin_approve_whatsapp_market_with_preview($1,1,$2,true,true,$3)',[s.inbox,p.preview_hash,'Verified WhatsApp acceptance']),/Gere um novo resumo/);assert.equal(await scalar('select count(*) from public.transactions'),0);});
  await run('closing reconciliation detects financial drift and checks compensations',async()=>{const s=await scenario(),p=await correct(s);await correct(s,true,p.preview_hash);const ok=await scalar('select public.admin_reconcile_whatsapp_market_window()');assert.deepEqual(ok.issues,[]);await client.query('update public.clubs set balance=999 where id=$1',[s.buyer]);assert.equal((await scalar('select public.admin_reconcile_whatsapp_market_window()')).issues[0].kind,'balance');});
  await run('non ADMs and anonymous clients cannot use correction or edit evidence',async()=>{const s=await scenario();assert.equal(await scalar("select has_function_privilege('anon','public.admin_correct_whatsapp_market_settlement(uuid,uuid,text,boolean,text)','execute')"),false);assert.equal(await scalar("select has_table_privilege('authenticated','public.whatsapp_market_corrections','insert')"),false);await client.query("select set_config('mlg_test.actor',$1,true)",[randomUUID()]);await negative(()=>correct(s),/Somente ADMs/);});
  await run('incomplete original cash effects cannot create settlement evidence',async()=>{const s=await scenario('transfer',false,false);await client.query("update public.negotiations set status='executed' where id=$1",[s.source]);await client.query('update public.players set club_id=$1 where id=$2',[s.buyer,s.p]);await negative(()=>client.query("update public.whatsapp_market_inbox set status='settled' where id=$1",[s.inbox]),/Caixa da liquidação não confere/);assert.equal(await scalar('select count(*) from public.whatsapp_market_settlement_snapshots'),0);});
  client.release();
 }finally{await db.end();await admin.query('drop database '+dbname);await admin.end();}
});
