import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {Pool} from 'pg';

test('negative-balance policy in disposable PostgreSQL',{skip:!process.env.MLG_TEST_DATABASE_URL},async t=>{
 const root=new Pool({connectionString:process.env.MLG_TEST_DATABASE_URL}),name='mlg_overdraft_'+randomUUID().replaceAll('-','');await root.query('create database '+name);const url=new URL(process.env.MLG_TEST_DATABASE_URL!);url.pathname='/'+name;const db=new Pool({connectionString:url.toString()});
 try{
  for(const f of ['mlg-window-integrity-base.sql','mlg-window-resilience-base.sql','mlg-window-resilience-contracts.sql','mlg-window-ledger.sql','mlg-window-integrity.sql','mlg-window-corrected-quotas.sql','mlg-window-reconcile.sql','mlg-window-resilience.sql','mlg-window-health.sql','mlg-window-safety-bridge.sql'])await db.query(await readFile(new URL('./fixtures/'+f,import.meta.url),'utf8'));
  await db.query('alter table public.market_windows add column max_transfers_per_club integer default 4');
  await db.query("create table public.club_transfer_bans(club_id uuid,status text,starts_at timestamptz,ends_at timestamptz,scope text,scope_rules jsonb);alter table public.free_agents add column card_image_url text,add column original_club_name text;alter table public.players alter column id set default gen_random_uuid();alter table public.players add column market_value bigint,add column category text,add column card_image_url text,add column meta jsonb");
  await db.query(await readFile(new URL('./fixtures/mlg-window-overdraft.sql',import.meta.url),'utf8'));
  await db.query(await readFile(new URL('./fixtures/mlg-window-overdraft-contracts.sql',import.meta.url),'utf8'));
  for(const f of ['mlg-window-overdraft-ban-compatibility.sql','mlg-window-overdraft-notices.sql','mlg-window-overdraft-bridge.sql'])await db.query(await readFile(new URL('./fixtures/'+f,import.meta.url),'utf8'));
  const actor=randomUUID(),cycle=randomUUID();await db.query('insert into auth.users values($1)',[actor]);await db.query('insert into public.admin_users values($1)',[actor]);await db.query('insert into public.market_windows(market_cycle_id) values($1)',[cycle]);await db.query('insert into public.platform_member_access values(true,true)');const c=await db.connect();await c.query("select set_config('mlg_test.actor',$1,false)",[actor]);
  const value=async(sql:string,args:any[]=[])=>Object.values((await c.query(sql,args)).rows[0])[0] as any;
  async function seed(){const buyer=randomUUID(),seller=randomUUID(),p=randomUUID();await c.query("insert into public.clubs(id,name,balance) values($1,'Buyer',100),($2,'Seller',0)",[buyer,seller]);await c.query("insert into public.players(id,club_id,name) values($1,$2,'Player')",[p,seller]);return {buyer,seller,p};}
  async function proposal(s:Awaited<ReturnType<typeof seed>>,amount:number,p=s.p){const n=randomUUID(),inbox=randomUUID();await c.query("insert into public.negotiations(id,type,club_a_id,club_b_id,player_ids_b,cash_from_a,status,market_cycle_id) values($1,'transfer',$2,$3,$4,$5,'open',$6)",[n,s.buyer,s.seller,JSON.stringify([p]),amount,cycle]);await c.query("insert into public.whatsapp_market_inbox(id,status,kind,negotiation_id,from_club_id,to_club_id,amount,player_ids_from,market_cycle_id) values($1,'awaiting_signatures','transfer',$2,$3,$4,$5,$6,$7)",[inbox,n,s.seller,s.buyer,amount,[p],cycle]);return {n,inbox};}
  let sanctioned:Awaited<ReturnType<typeof seed>>;let penalty:any;
  await t.test('overspending settles both ledgers and roster, then immediately bans future movements',async()=>{sanctioned=await seed();const r=await proposal(sanctioned,120);const preview=await value('select public.admin_preview_whatsapp_market_approval($1,1)',[r.inbox]);assert.equal(preview.clubs.find((x:any)=>x.id===sanctioned.buyer).after,-20);await value('select public.admin_approve_whatsapp_market_with_preview($1,1,$2)',[r.inbox,preview.preview_hash]);assert.equal(Number(await value('select balance from public.clubs where id=$1',[sanctioned.buyer])),-20);assert.equal(Number(await value('select balance from public.clubs where id=$1',[sanctioned.seller])),120);assert.equal(await value('select club_id from public.players where id=$1',[sanctioned.p]),sanctioned.buyer);penalty=await value('select to_jsonb(p) from public.market_balance_penalties p where club_id=$1',[sanctioned.buyer]);assert.equal(penalty.penalty,'all_market');await assert.rejects(()=>proposal(sanctioned,1),/Transfer Ban/);await assert.rejects(()=>c.query("insert into public.negotiations(id,type,club_a_id,club_b_id,status,market_cycle_id) values($1,'trade',$2,$3,'open',$4)",[randomUUID(),sanctioned.seller,sanctioned.buyer,cycle]),/Transfer Ban/);const replay=await value('select public.admin_approve_whatsapp_market_with_preview($1,1,$2)',[r.inbox,preview.preview_hash]);assert.equal(replay.duplicate,true);assert.equal(Number(await value('select count(*) from public.market_balance_penalties where club_id=$1',[sanctioned.buyer])),1);});
  await t.test('zero balance is valid and rejected/cancelled proposals do not apply bans',async()=>{const s=await seed(),r=await proposal(s,100);await c.query("update public.negotiations set status='accepted' where id=$1",[r.n]);await c.query('select public.execute_negotiation($1)',[r.n]);assert.equal(Number(await value('select balance from public.clubs where id=$1',[s.buyer])),0);assert.equal(Number(await value('select count(*) from public.market_balance_penalties where club_id=$1',[s.buyer])),0);const s2=await seed(),r2=await proposal(s2,150);await c.query("update public.negotiations set status='cancelled' where id=$1",[r2.n]);assert.equal(Number(await value('select count(*) from public.market_balance_penalties where club_id=$1',[s2.buyer])),0);});
  await t.test('ADM may reduce one purchase; stale revisions and non-ADM decisions are refused',async()=>{await value('select public.admin_review_market_balance_penalty($1,1,$2,$3)',[penalty.id,'one_purchase','ADM reviewed proportional penalty']);await assert.rejects(()=>value('select public.admin_review_market_balance_penalty($1,1,$2,$3)',[penalty.id,'lifted','Stale administrative decision']),/mudou/);await c.query("select set_config('mlg_test.actor','',false)");await assert.rejects(()=>value('select public.admin_review_market_balance_penalty($1,2,$2,$3)',[penalty.id,'lifted','Unauthorized administrative decision']),/Somente ADMs/);await c.query("select set_config('mlg_test.actor',$1,false)",[actor]);await value('select private.check_market_balance_penalty($1,$2,1)',[sanctioned.buyer,cycle]);for(let i=0;i<2;i++){const p=randomUUID();await c.query("insert into public.players(id,club_id,name) values($1,$2,'Extra')",[p,sanctioned.seller]);await proposal(sanctioned,1,p);}await assert.rejects(()=>value('select private.check_market_balance_penalty($1,$2,1)',[sanctioned.buyer,cycle]),/uma compra/);});
  await t.test('pending contracts cannot bypass a full ban at approval',async()=>{const s=await seed(),r=await proposal(s,20),p=randomUUID();await c.query("insert into public.players(id,club_id,name) values($1,$2,'Breach')",[p,s.seller]);const breach=await proposal(s,120,p);await c.query("update public.negotiations set status='accepted' where id=$1",[breach.n]);await c.query('select public.execute_negotiation($1)',[breach.n]);await assert.rejects(()=>c.query("update public.negotiations set status='accepted' where id=$1",[r.n]),/Transfer Ban/);assert.equal(await value('select club_id from public.players where id=$1',[s.p]),s.seller);});
  await t.test('concurrent approval waits for the breach settlement and cannot escape its ban',async()=>{const s=await seed(),r=await proposal(s,120),p=randomUUID();await c.query("insert into public.players(id,club_id,name) values($1,$2,'Concurrent')",[p,s.seller]);const second=await proposal(s,20,p);const a=await db.connect(),b=await db.connect();try{for(const x of [a,b]){await x.query('begin');await x.query("select set_config('mlg_test.actor',$1,true)",[actor]);await x.query("set local statement_timeout='5s'");}const pid=(await b.query('select pg_backend_pid() pid')).rows[0].pid;await a.query("update public.negotiations set status='accepted' where id=$1",[r.n]);await a.query('select public.execute_negotiation($1)',[r.n]);const attempt=b.query("update public.negotiations set status='accepted' where id=$1",[second.n]).then(()=>null,e=>e);let blocked=false;for(let i=0;i<100;i++){const row=(await db.query('select wait_event_type from pg_stat_activity where pid=$1',[pid])).rows[0];if(row?.wait_event_type==='Lock'){blocked=true;break;}await new Promise(r=>setTimeout(r,10));}assert.equal(blocked,true);await a.query('commit');assert.match(String(await attempt),/Transfer Ban/);assert.equal(Number(await value('select balance from public.clubs where id=$1',[s.buyer])),-20);}finally{await a.query('rollback');await b.query('rollback');a.release();b.release();}});
  await t.test('external signed purchases also settle negative balance and apply the same ban',async()=>{const s=await seed(),agent=randomUUID(),tr=randomUUID();await c.query("insert into public.free_agents(id,name,market_value,status) values($1,'External',120,'available')",[agent]);await c.query("insert into public.transfers(id,free_agent_id,to_club_id,price,status,market_cycle_id) values($1,$2,$3,120,'pending',$4)",[tr,agent,s.buyer,cycle]);await value('select public.admin_approve_signed_transfer($1)',[tr]);assert.equal(Number(await value('select balance from public.clubs where id=$1',[s.buyer])),-20);assert.equal(await value('select status from public.free_agents where id=$1',[agent]),'acquired');assert.equal(await value('select private.club_has_active_ban($1)',[s.buyer]),true);});
  await t.test('ADM WhatsApp notices use durable leases and acknowledge only the current delivery',async()=>{const token='b'.repeat(64);await c.query("insert into private.whatsapp_market_credentials values(encode(sha256(convert_to($1,'UTF8')),'hex'))",[token]);const notices=await value('select public.bot_whatsapp_market_gate($1,$2,$3)',[token,'claim_admin',{groups:['12345@g.us']}]);assert.equal(notices.notices.length,4);const second=await value('select public.bot_whatsapp_market_gate($1,$2,$3)',[token,'claim_admin',{groups:['12345@g.us']}]);assert.equal(second.notices.length,0);const n=notices.notices[0];assert.equal((await value('select public.bot_whatsapp_market_gate($1,$2,$3)',[token,'ack_admin',{id:n.id,lease:n.lease,sent:true}])).success,true);assert.equal((await value('select public.bot_whatsapp_market_gate($1,$2,$3)',[token,'ack_admin',{id:n.id,lease:n.lease,sent:true}])).success,false);});
  await t.test('a new cycle expires sanctions, preserves breach evidence and permits transfers again',async()=>{await c.query('update public.market_windows set market_cycle_id=$1',[randomUUID()]);assert.equal(await value('select penalty from public.market_balance_penalties where id=$1',[penalty.id]),'expired');await value('select private.check_market_balance_penalty($1,$2,1)',[sanctioned.buyer,randomUUID()]);assert.equal(Number(await value("select count(*) from public.audit_logs where action='market_balance_penalty_expired'")),4);assert.equal(Number(await value('select balance_at_breach from public.market_balance_penalties where id=$1',[penalty.id])),-20);});
  c.release();
 }finally{await db.end();await root.query('drop database '+name);await root.end();}
});
