import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {Pool} from 'pg';

test('negative-balance policy in disposable PostgreSQL',{skip:!process.env.MLG_TEST_DATABASE_URL},async t=>{
 const root=new Pool({connectionString:process.env.MLG_TEST_DATABASE_URL}),name='mlg_overdraft_'+randomUUID().replaceAll('-','');await root.query('create database '+name);const url=new URL(process.env.MLG_TEST_DATABASE_URL!);url.pathname='/'+name;const db=new Pool({connectionString:url.toString()});
 try{
  for(const f of ['mlg-window-integrity-base.sql','mlg-window-resilience-base.sql','mlg-window-resilience-contracts.sql','mlg-window-ledger.sql','mlg-window-integrity.sql','mlg-window-corrected-quotas.sql','mlg-window-reconcile.sql','mlg-window-resilience.sql','mlg-window-health.sql','mlg-window-safety-bridge.sql'])await db.query(await readFile(new URL('./fixtures/'+f,import.meta.url),'utf8'));
  await db.query('alter table public.market_windows add column max_transfers_per_club integer default 4');
  await db.query(await readFile(new URL('./fixtures/mlg-window-overdraft.sql',import.meta.url),'utf8'));
  await db.query(await readFile(new URL('./fixtures/mlg-window-overdraft-contracts.sql',import.meta.url),'utf8'));
  const actor=randomUUID(),cycle=randomUUID();await db.query('insert into auth.users values($1)',[actor]);await db.query('insert into public.admin_users values($1)',[actor]);await db.query('insert into public.market_windows(market_cycle_id) values($1)',[cycle]);await db.query('insert into public.platform_member_access values(true,true)');const c=await db.connect();await c.query("select set_config('mlg_test.actor',$1,false)",[actor]);
  const value=async(sql:string,args:any[]=[])=>Object.values((await c.query(sql,args)).rows[0])[0] as any;
  async function seed(){const buyer=randomUUID(),seller=randomUUID(),p=randomUUID();await c.query("insert into public.clubs(id,name,balance) values($1,'Buyer',100),($2,'Seller',0)",[buyer,seller]);await c.query("insert into public.players(id,club_id,name) values($1,$2,'Player')",[p,seller]);return {buyer,seller,p};}
  async function proposal(s:Awaited<ReturnType<typeof seed>>,amount:number,p=s.p){const n=randomUUID(),inbox=randomUUID();await c.query("insert into public.negotiations(id,type,club_a_id,club_b_id,player_ids_b,cash_from_a,status,market_cycle_id) values($1,'transfer',$2,$3,$4,$5,'open',$6)",[n,s.buyer,s.seller,JSON.stringify([p]),amount,cycle]);await c.query("insert into public.whatsapp_market_inbox(id,status,kind,negotiation_id,from_club_id,to_club_id,amount,player_ids_from,market_cycle_id) values($1,'awaiting_signatures','transfer',$2,$3,$4,$5,$6,$7)",[inbox,n,s.seller,s.buyer,amount,[p],cycle]);return {n,inbox};}
  let sanctioned:Awaited<ReturnType<typeof seed>>;let penalty:any;
  await t.test('overspending settles both ledgers and roster, then immediately bans future movements',async()=>{sanctioned=await seed();const r=await proposal(sanctioned,120);const preview=await value('select public.admin_preview_whatsapp_market_approval($1,1)',[r.inbox]);assert.equal(preview.clubs.find((x:any)=>x.id===sanctioned.buyer).after,-20);await value('select public.admin_approve_whatsapp_market_with_preview($1,1,$2)',[r.inbox,preview.preview_hash]);assert.equal(Number(await value('select balance from public.clubs where id=$1',[sanctioned.buyer])),-20);assert.equal(Number(await value('select balance from public.clubs where id=$1',[sanctioned.seller])),120);assert.equal(await value('select club_id from public.players where id=$1',[sanctioned.p]),sanctioned.buyer);penalty=await value('select to_jsonb(p) from public.market_balance_penalties p where club_id=$1',[sanctioned.buyer]);assert.equal(penalty.penalty,'all_market');await assert.rejects(()=>proposal(sanctioned,1),/Transfer Ban/);await assert.rejects(()=>c.query("insert into public.negotiations(id,type,club_a_id,club_b_id,status,market_cycle_id) values($1,'trade',$2,$3,'open',$4)",[randomUUID(),sanctioned.seller,sanctioned.buyer,cycle]),/Transfer Ban/);const replay=await value('select public.admin_approve_whatsapp_market_with_preview($1,1,$2)',[r.inbox,preview.preview_hash]);assert.equal(replay.duplicate,true);assert.equal(Number(await value('select count(*) from public.market_balance_penalties where club_id=$1',[sanctioned.buyer])),1);});
  await t.test('zero balance is valid and rejected/cancelled proposals do not apply bans',async()=>{const s=await seed(),r=await proposal(s,100);await c.query("update public.negotiations set status='accepted' where id=$1",[r.n]);await c.query('select public.execute_negotiation($1)',[r.n]);assert.equal(Number(await value('select balance from public.clubs where id=$1',[s.buyer])),0);assert.equal(Number(await value('select count(*) from public.market_balance_penalties where club_id=$1',[s.buyer])),0);const s2=await seed(),r2=await proposal(s2,150);await c.query("update public.negotiations set status='cancelled' where id=$1",[r2.n]);assert.equal(Number(await value('select count(*) from public.market_balance_penalties where club_id=$1',[s2.buyer])),0);});
  await t.test('ADM may reduce one purchase; stale revisions and non-ADM decisions are refused',async()=>{await value('select public.admin_review_market_balance_penalty($1,1,$2,$3)',[penalty.id,'one_purchase','ADM reviewed proportional penalty']);await assert.rejects(()=>value('select public.admin_review_market_balance_penalty($1,1,$2,$3)',[penalty.id,'lifted','Stale administrative decision']),/mudou/);await c.query("select set_config('mlg_test.actor','',false)");await assert.rejects(()=>value('select public.admin_review_market_balance_penalty($1,2,$2,$3)',[penalty.id,'lifted','Unauthorized administrative decision']),/Somente ADMs/);await c.query("select set_config('mlg_test.actor',$1,false)",[actor]);await value('select private.check_market_balance_penalty($1,$2,1)',[sanctioned.buyer,cycle]);for(let i=0;i<2;i++){const p=randomUUID();await c.query("insert into public.players(id,club_id,name) values($1,$2,'Extra')",[p,sanctioned.seller]);await proposal(sanctioned,1,p);}await assert.rejects(()=>value('select private.check_market_balance_penalty($1,$2,1)',[sanctioned.buyer,cycle]),/uma compra/);});
  await t.test('pending contracts cannot bypass a full ban at approval',async()=>{const s=await seed(),r=await proposal(s,20),p=randomUUID();await c.query("insert into public.players(id,club_id,name) values($1,$2,'Breach')",[p,s.seller]);const breach=await proposal(s,120,p);await c.query("update public.negotiations set status='accepted' where id=$1",[breach.n]);await c.query('select public.execute_negotiation($1)',[breach.n]);await assert.rejects(()=>c.query("update public.negotiations set status='accepted' where id=$1",[r.n]),/Transfer Ban/);assert.equal(await value('select club_id from public.players where id=$1',[s.p]),s.seller);});
  await t.test('a new cycle expires sanctions, preserves breach evidence and permits transfers again',async()=>{await c.query('update public.market_windows set market_cycle_id=$1',[randomUUID()]);assert.equal(await value('select penalty from public.market_balance_penalties where id=$1',[penalty.id]),'expired');await value('select private.check_market_balance_penalty($1,$2,1)',[sanctioned.buyer,randomUUID()]);assert.equal(Number(await value("select count(*) from public.audit_logs where action='market_balance_penalty_expired'")),2);assert.equal(Number(await value('select balance_at_breach from public.market_balance_penalties where id=$1',[penalty.id])),-20);});
  c.release();
 }finally{await db.end();await root.query('drop database '+name);await root.end();}
});
