import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{readFile}from'node:fs/promises';import{Pool}from'pg';
test('window trust and automatic signals in disposable PostgreSQL',{skip:!process.env.MLG_TEST_DATABASE_URL},async t=>{
 const root=new Pool({connectionString:process.env.MLG_TEST_DATABASE_URL}),name='mlg_trust_'+randomUUID().replaceAll('-','');await root.query('create database '+name);const url=new URL(process.env.MLG_TEST_DATABASE_URL!);url.pathname='/'+name;const db=new Pool({connectionString:url.toString()});
 try{
  for(const f of['mlg-window-integrity-base.sql','mlg-window-resilience-base.sql','mlg-window-ledger.sql','mlg-window-integrity.sql','mlg-window-corrected-quotas.sql','mlg-window-overdraft.sql','mlg-window-trust-base.sql','mlg-window-trust-and-signals.sql'])await db.query(await readFile(new URL('./fixtures/'+f,import.meta.url),'utf8'));
  const actor=randomUUID(),cycle=randomUUID(),buyer=randomUUID(),seller=randomUUID(),player=randomUUID();
  await db.query('insert into auth.users(id) values($1)',[actor]);await db.query('insert into public.admin_users values($1)',[actor]);await db.query("select set_config('mlg_test.actor',$1,false)",[actor]);
  await db.query('insert into public.market_windows(market_cycle_id) values($1)',[cycle]);await db.query("insert into public.market_module_policies(module) values('transfer'),('trade')");
  await db.query("insert into public.clubs(id,name,balance) values($1,'Buyer',100),($2,'Seller',100)",[buyer,seller]);await db.query("insert into public.players(id,club_id,name) values($1,$2,'Current Player')",[player,seller]);await db.query("insert into public.whatsapp_market_club_directory values($1,'Buyer Coach','5511111111111'),($2,'Seller Coach','5522222222222')",[buyer,seller]);
  const value=async(sql:string,args:any[]=[])=>Object.values((await db.query(sql,args)).rows[0])[0] as any;
  for(let i=0;i<4;i++)await db.query("insert into public.negotiations(id,type,club_a_id,club_b_id,player_ids_b,status,market_cycle_id) values($1,'transfer',$2,$3,$4,'executed',$5)",[randomUUID(),buyer,seller,JSON.stringify([randomUUID()]),cycle]);
  await t.test('concluded count excludes rejected and pending operations and counts internal purchases once',async()=>{await db.query("insert into public.negotiations(id,type,club_a_id,club_b_id,player_ids_b,status,market_cycle_id) values($1,'transfer',$2,$3,$4,'rejected',$5),($6,'transfer',$2,$3,$4,'open',$5)",[randomUUID(),buyer,seller,JSON.stringify([player]),cycle,randomUUID()]);assert.equal((await value('select private.market_window_completed_usage($1,$2)',[buyer,cycle])).purchases,4);assert.equal((await value('select private.market_window_usage($1,$2)',[buyer,cycle])).purchases,5);await db.query("delete from public.negotiations where status<>'executed'");});
  let inbox:string;
  await t.test('fifth purchase is flagged for ADMs; fifth sale is automatically rejected; no balance changes',async()=>{inbox=randomUUID();await db.query("insert into public.whatsapp_market_inbox(id,kind,status,participant_id,parsed,market_cycle_id) values($1,'transfer','received','5511111111111@s.whatsapp.net',$2,$3)",[inbox,{origin:'Seller',destination:'Buyer',playersFrom:['Current Player'],issues:[],purchaseScope:'internal'},cycle]);const row=await value('select to_jsonb(i) from public.whatsapp_market_inbox i where id=$1',[inbox]);assert.equal(row.status,'rejected');assert.equal(row.automatic_rejection,true);assert.deepEqual(row.quota_flags.map((f:any)=>f.type),['purchase','sale']);assert.match(row.classification_note,/Buyer Coach.*4\/4.*Seller Coach/);assert.equal(Number(await value('select balance from public.clubs where id=$1',[buyer])),100);assert.equal(Number(await value('select count(*) from private.whatsapp_market_private_notices')),2);assert.equal(await value('select emoji from public.test_reactions limit 1'),'❌');});
  await t.test('quota warning reaches ADM group immediately with club, responsible and exceeded limit',async()=>{const n=await value("select private.claim_whatsapp_market_admin_notices('[\"12345@g.us\"]')");assert.equal(n.notices.length,1);assert.match(n.notices[0].body,/Buyer Coach.*Buyer.*4\/4.*Seller Coach/);assert.equal((await value("select private.claim_whatsapp_market_admin_notices('[\"12345@g.us\"]')")).notices.length,0);});
  await t.test('ADM retracts automatic mark without financial effects or recurring alert',async()=>{const r=await value('select public.admin_retract_whatsapp_market_classification($1,1,$2,$3)',[inbox!,'internal','ADM corrected synthetic classification']);assert.equal(r.financial_effect,false);assert.deepEqual(await value('select quota_flags from public.whatsapp_market_inbox where id=$1',[inbox!]),[]);assert.equal(await value('select emoji from public.test_reactions order by ctid desc limit 1'),'');});
  await t.test('trust consumes one trade for one purchase, refuses retroactive loss of consumed capacity',async()=>{const r=await value('select public.admin_set_market_club_option($1,true,null,$2)',[buyer,'Member explicitly chose trust conversion']);assert.equal(r.limits.purchase_limit,5);assert.equal(r.limits.trade_limit,1);await db.query('create trigger quota_guard before insert or update on public.negotiations for each row execute function private.guard_market_window_quota()');await db.query("update public.negotiations set club_b_id=$1 where status='executed'",[randomUUID()]);const n=randomUUID();await db.query("insert into public.negotiations(id,type,club_a_id,club_b_id,player_ids_b,cash_from_a,status,market_cycle_id) values($1,'transfer',$2,$3,$4,1,'open',$5)",[n,buyer,seller,JSON.stringify([player]),cycle]);await assert.rejects(()=>db.query('select public.admin_set_market_club_option($1,false,null,$2)',[buyer,'Cannot remove already reserved capacity']),/conflita/);await assert.rejects(()=>db.query("insert into public.negotiations(id,type,club_a_id,club_b_id,player_ids_b,cash_from_a,status,market_cycle_id) values($1,'transfer',$2,$3,$4,1,'open',$5)",[randomUUID(),buyer,seller,JSON.stringify([player]),cycle]),/Limite de compras/);});
  await t.test('purchase above four remains reversible human review when seller has remaining quota',async()=>{const id=randomUUID();await db.query("insert into public.whatsapp_market_inbox(id,kind,status,participant_id,parsed,market_cycle_id) values($1,'transfer','received','5511111111111@s.whatsapp.net',$2,$3)",[id,{origin:'Seller',destination:'Buyer',playersFrom:['Current Player'],issues:[],purchaseScope:'internal'},cycle]);const row=await value('select to_jsonb(i) from public.whatsapp_market_inbox i where id=$1',[id]);assert.equal(row.status,'needs_review');assert.equal(row.automatic_rejection,false);assert.deepEqual(row.quota_flags.map((f:any)=>f.type),['purchase']);});
  await t.test('explicit ADM exception permits sixth purchase without raising other clubs or sales quotas',async()=>{const r=await value('select public.admin_set_market_club_option($1,true,6,$2)',[buyer,'ADM reviewed and authorized sixth purchase']);assert.equal(r.limits.purchase_limit,6);assert.equal(r.limits.sale_limit,4);assert.equal((await value('select private.market_effective_limits($1,$2)',[seller,cycle])).purchase_limit,4);});
  await t.test('confidence permits only one trade and a second trade is refused',async()=>{const pa=randomUUID(),pb=randomUUID();await db.query("insert into public.players(id,club_id,name) values($1,$2,'Trade A'),($3,$4,'Trade B')",[pa,buyer,pb,seller]);const sql="insert into public.negotiations(id,type,club_a_id,club_b_id,status,market_cycle_id,player_ids_a,player_ids_b) values($1,'trade',$2,$3,'open',$4,$5,$6)";const args=[buyer,seller,cycle,JSON.stringify([pa]),JSON.stringify([pb])];await db.query(sql,[randomUUID(),...args]);await assert.rejects(()=>db.query(sql,[randomUUID(),...args]),/Limite de trocas/);});
  await t.test('negative balance records pending review and does not automatically impose Transfer Ban',async()=>{await db.query("insert into public.transactions(club_id,type,amount,description) values($1,'negotiation_payment',-150,'Synthetic signed expense')",[buyer]);assert.equal(await value('select penalty from public.market_balance_penalties where club_id=$1',[buyer]),'pending_review');await db.query('select private.check_market_balance_penalty($1,$2,1)',[buyer,cycle]);});
  await t.test('closed window rejects options instead of losing them in next cycle',async()=>{await db.query('update public.market_windows set transfer_window_open=false');await assert.rejects(()=>db.query('select public.admin_set_market_club_option($1,true,6,$2)',[buyer,'This must wait until the new window opens']),/Abra a janela/);await db.query('update public.market_windows set transfer_window_open=true');});
  await t.test('anonymous and non ADM callers cannot authorize confidence or exceptional purchases',async()=>{assert.equal(await value("select has_function_privilege('anon','public.admin_set_market_club_option(uuid,boolean,integer,text)','execute')"),false);assert.equal(await value("select has_table_privilege('authenticated','public.market_window_club_options','insert')"),false);await db.query("select set_config('mlg_test.actor','',false)");await assert.rejects(()=>db.query('select public.admin_set_market_club_option($1,true,99,$2)',[buyer,'Unauthorized quota increase']),/Somente ADMs/);});
 }finally{await db.end();await root.query('drop database '+name);await root.end();}
});
