// Original jokes inspired by recurring football topics; no private transcript or inferred personal facts.
export const banks = {
 defeat: [
 'Nem começou e tu já tá preparando a coletiva de desculpas 😂',
 'Entra em campo primeiro, a entrevista do eliminado é depois 😂',
 'Calma, ainda dá tempo de surpreender até essa tua previsão 🎮',
 'A escalação saiu ou isso já é a nota de despedida? 😂',
 'Tu tá aquecendo o time ou a justificativa?',
 'Pelo menos espera o adversário ligar o console pra entregar os pontos 😂',
 'Confiança tão alta que o ônibus já tá apontado pra saída.',
 'Se pessimismo marcasse gol, tu entrava com vantagem 😂',
 'O jogo nem carregou e a coletiva já tá ao vivo 🍿',
 'Vai jogar ou vai mandar o resultado por previsão do tempo?',
 'Primeiro aperta iniciar. O discurso triste a gente revisa depois 😂',
 'O adversário ainda tá escolhendo uniforme e tu já escolheu a desculpa.'
 ],
 market: [
 'Fechou o elenco ou só fechou a aba do mercado? 😂',
 'Nesse ritmo o contrato vem com período de teste de quinze minutos.',
 'O empresário já deixou o carregador na sede do clube 📱😂',
 'A janela fecha, mas o privado continua aberto.',
 'Tem mais proposta nesse grupo do que chute dentro da área 😂',
 'O reforço nem escolheu o número e já perguntaram quanto custa vender.',
 'Calma, diretor. O botão de contratar não substitui o de marcar 😂',
 'O departamento de futebol tá precisando de férias e um contador.',
 'Já tem anúncio ou ainda tá na fase de mandar olhinho no privado? 👀',
 'O contrato foi assinado a lápis? Toda hora tem atualização 😂',
 'Montar esse elenco tá virando modo carreira dentro do WhatsApp.',
 'A negociação começou com bom dia e terminou pedindo metade do time.',
 'A proposta tá tão criativa que merece prêmio de roteiro 😂',
 'Esse elenco fechado tem mais entrada que shopping no sábado.'
 ],
 complaints: [
 'O apito final tocou e a perícia do controle começou 😂',
 'Vai ter mais análise desse jogo do que treino pra próxima partida 🍿',
 'A coletiva promete prorrogação hoje 😂',
 'O relatório da partida já tá maior que o regulamento?',
 'Se a explicação tivesse assistência, hoje era líder do ranking 😂',
 'A sala de replay tá aberta. A de treino também, só lembrando.',
 'O pós-jogo ganhou departamento jurídico 🍿',
 'O placar acabou; a investigação ainda tá no primeiro capítulo.',
 'Tem coletiva, réplica e direito a tréplica nesse campeonato? 😂',
 'A discussão já teve mais acréscimos que a partida.',
 'Vou buscar café, porque esse lance ainda vai render três versões.',
 'O controle pediu pra ser ouvido antes de virar o único culpado 😂'
 ],
 lag: [
 'O Wi-Fi virou o terceiro técnico desse confronto 😂',
 'Se o ping desse entrevista, esse grupo virava documentário.',
 'Reinicia o roteador e deixa a coletiva em espera 🎮',
 'O passe chegou depois do comentário sobre ele 😂',
 'Hoje o meio-campo tá funcionando por correspondência?',
 'O boneco girou ou tá aguardando confirmação do provedor?',
 'Até o replay tá pedindo uma conexão melhor.',
 'O lateral ficou parado ou entrou no modo economia de dados? 😂',
 'A bola foi lançada. A previsão de entrega é outra história.',
 'O roteador acaba de pedir substituição 😂',
 'Nesse ping até o contra-ataque precisa agendar horário.',
 'A conexão merece avaliação; a resenha já tá em velocidade máxima 🍿'
 ],
 victory: [
 'Ganhou o jogo e desbloqueou o pacote de entrevistas 😂',
 'O pós-jogo desse grupo devia ter transmissão própria 🍿',
 'Já tô vendo: noventa minutos de jogo e três dias de resenha.',
 'A comemoração já tá pedindo um grupo só pra ela 😂',
 'Calma com a volta olímpica, ainda tem gente procurando o replay.',
 'O print do placar vai rodar mais que a bola hoje.',
 'Vitória no console, assessoria de imprensa no WhatsApp 😂',
 'Já pode tirar o uniforme de jogo e vestir o de comentarista.',
 'A coletiva de quem ganhou costuma começar sem ninguém perguntar 😂',
 'Esse resultado vai aparecer até em conversa sobre bom dia.',
 'Ganhou três pontos e uma semana de assunto? 🍿',
 'O apito encerrou o jogo, mas aparentemente abriu a turnê.'
 ],
 escape: [
 'A velocidade apareceu justamente na hora de fugir do confronto 😂',
 'Essa arrancada fora do campo precisa entrar nos melhores momentos.',
 'O convite chegou e o status entrou em modo avião? 😂',
 'Tem que marcar o jogo ou pedir audiência?',
 'A agenda ficou lotada bem na hora do confronto 🍿',
 'O adversário chamou e começou a manutenção preventiva do console.',
 'O ônibus tá tão recuado que saiu do estádio 😂',
 'Cadê o botão de aceitar amistoso nessa formação?',
 'A estratégia é pressionar alto ou desaparecer baixo?',
 'Esse aquecimento tá acontecendo em localização desconhecida 😂',
 'Pode sair da retranca do WhatsApp, o jogo ainda nem começou.',
 'A marcação tá individual: um chama, o outro some 🍿'
 ],
 tactics: [
 'Essa formação veio da prancheta ou do sorteio? 😂',
 'Tem tanto atacante que o zagueiro vai cobrar adicional de função.',
 'O ônibus tá estacionado ou já fizeram garagem dentro da área?',
 'Bonito no desenho. Agora falta convencer os bonecos 🎮',
 'Esse meio-campo tá vazio pra receber reforço?',
 'O lateral sobe, mas alguém avisou quem fica?',
 'A tática tá fluida: uma hora parece organizada, outra ninguém acha a bola 😂',
 'Antes de mexer na formação, confere se todo mundo entendeu pra qual lado ataca.',
 'Tem mais seta nessa prancheta do que no trânsito.',
 'O plano B é mudar tudo ou reclamar do plano A? 😂',
 'Essa pressão alta precisa vir com fôlego e um plano de volta.',
 'A retranca tá tão compacta que o goleiro pediu espaço pra respirar.'
 ],
 rematch: [
 'Revanche marcada: novo jogo, mesmas testemunhas 🍿',
 'Pode pedir a volta. Só não vale devolver o controle junto 😂',
 'A revanche é no console; o trailer já começou aqui.',
 'Agora tem jogo e acerto de contas com o próprio replay 🎮',
 'O segundo capítulo costuma vir com mais promessa que o primeiro.',
 'Vai buscar o troco ou só atualizar a nota oficial? 😂',
 'Esse reencontro tá pedindo pipoca e bateria no controle.',
 'A melhor resposta é em campo. O grupo aceita o print depois.',
 'Revanche boa começa no convite e termina sem sumiço 🍿',
 'Já tem data ou é só prévia da próxima coletiva?',
 'O roteiro tá aberto. Não entrega o final antes de jogar 😂',
 'O jogo de volta vem com revisão de tática ou só discurso novo?'
 ],
 penalties: [
 'Pênalti: a hora em que até o analógico fica nervoso 😂',
 'Escolhe o canto antes de negociar com o universo.',
 'Agora a prancheta dá lugar à respiração funda 🎮',
 'O goleiro tá esperando a bola ou lendo o grupo?',
 'Tem gente que bate o pênalti e só depois decide o canto 😂',
 'Essa caminhada até a bola demora mais que a negociação de reforço.',
 'Na marca da cal, a resenha fica em silêncio por três segundos 🍿',
 'Cavadinha é linda. A explicação quando erra também costuma ser criativa.',
 'O controle precisa de firmeza; o grupo já tá pronto pro replay.',
 'Agora é escolher o canto e aceitar o pós-jogo 😂',
 'O goleiro piscou e já começaram cinco teorias.',
 'O pênalti dura um instante; o print pode durar a temporada.'
 ],
 tournament: [
 'Mata-mata: onde o discurso de favorito precisa entrar em campo 🍿',
 'A taça tá esperando futebol, não apresentação de PowerPoint 😂',
 'Final boa deixa o grupo sem assunto por uns cinco segundos.',
 'Nessa fase até escolher o uniforme parece decisão tática.',
 'O caminho até a taça passa pelo botão de iniciar 🎮',
 'A pressão aumentou e a bateria do controle virou patrimônio do clube.',
 'Pode preparar a chamada. A faixa de campeão espera o apito.',
 'Semifinal não aceita currículo: tem que jogar 🍿',
 'A taça ainda não tem dono, mas já tem assessor de imprensa sobrando.',
 'A festa tá planejada? Só falta combinar com o adversário 😂',
 'Quem avançar leva a vaga. O pós-jogo fica pra todo mundo.',
 'Hoje o amistoso ficou em casa. O nervosismo veio com a delegação.'
 ],
 draw: [
 'O sorteio montou a chave e terceirizou a confusão pro grupo 😂',
 'Se essa bolinha falasse, já tava dando entrevista 🍿',
 'O sorteio acabou; a análise de quem pegou caminho fácil só começou.',
 'Antes da bolinha todo mundo queria pedreira. Agora tão lendo o regulamento 😂',
 'Chave definida. Falta descobrir quem vai aparecer no horário.',
 'Esse sorteio tá com cara de grupo movimentado até amanhã.',
 'A bolinha escolhe o adversário. A desculpa cada um prepara a sua 😂',
 'Pode conferir a chave: ninguém sorteou vitória automática.',
 'O sorteio não aceita pedido de troca pelo privado 🍿',
 'Agora é preparar o time e parar de encarar a bolinha.',
 'A organização entregou confronto; vocês cuidam do entretenimento.',
 'Tá todo mundo olhando a chave como se fosse resultado de prova 😂'
 ],
 rout: [
 'O placar chamou atenção; agora segura a coletiva 🍿',
 'Esse pós-jogo vai precisar de moderador e café 😂',
 'Antes de comemorar o próximo gol, lembra que o grupo salva print.',
 'O replay vai render mais comentários que a escalação.',
 'Tem jogo que acaba e deixa pauta pra semana inteira.',
 'O goleiro vai querer participar da reunião tática 😂',
 'A análise defensiva vai começar pelo conceito de defender.',
 'Respira e reorganiza. O grupo não vai reorganizar a zoeira por você.',
 'O ataque teve assunto. A defesa vai precisar de explicação 🍿',
 'Já separaram os melhores momentos ou cabe a partida inteira?',
 'O placar é do jogo; o documentário é do grupo 😂',
 'Depois dessa conversa, o treino de marcação ganhou prioridade.'
 ],
 greeting: [
 'Cheguei. Já tem jogo ou só dirigente oferecendo jogador? 😂',
 'Salve! Qual é a pauta: futebol, mercado ou coletiva? 🎮',
 'Tô na área. Hoje o grupo tá em pré-jogo ou pós-desculpa?',
 'Fala, comissão técnica! Quem trouxe a bola? ⚽',
 'Presente. O controle tá carregado e a pipoca encaminhada 🍿',
 'Boa! O VAR do grupo já abriu os trabalhos?',
 'Salve, tropa. Pode puxar a resenha 😂',
 'Cheguei antes da próxima proposta de transferência.',
 'Na escuta. Tem confronto pra comentar?',
 'O banco tá ocupado. A resenha tá liberada 🎮',
 'Opa! Qual jogo vai virar assunto hoje?',
 'Bora. O futebol é virtual, a conversa vem de verdade 😂'
 ],
 general: [
 'Me dá o lance completo, que só a chamada não sustenta a coletiva 😂',
 'Quem tá envolvido nessa história? Preciso escalar a resenha direito.',
 'Explica essa jogada aí, que eu cheguei no meio do replay 🍿',
 'Isso é pré-jogo ou já começou a entrevista depois do apito?',
 'Qual é o contexto? Não vou inventar placar pra acompanhar a zoeira 🎮',
 'Solta o resto da história. Essa manchete veio sem a matéria.',
 'Tô acompanhando, mas faltou o passe antes dessa conclusão 😂',
 'Tem nome e confronto ou é provocação em aberto?',
 'Essa veio sem replay. Conta melhor 🍿',
 'Quem puxou essa pauta? Já tô procurando a coletiva.',
 'O grupo tá no modo debate. Me situa no assunto primeiro.',
 'Manda mais uma linha dessa história pra eu entrar no jogo 😂'
 ]
};
export type Topic=keyof typeof banks;
export function topicFor(text:string):Topic {
 const t=text.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const rules:[Topic,RegExp][]=[
 ['lag',/\b(lag|ping|internet|conexao|roteador|travando|travou)\b/],
 ['penalties',/\b(penalti|penaltis|penalty|penalties|cavadinha)\b/],
 ['rematch',/\b(revanche|troco|jogo de volta)\b/],
 ['draw',/\b(sorteio|sortear|bolinha|sorteado)\b/],
 ['rout',/\b(goleada|goleou|amassou|surra)\b/],
 ['defeat',/\b(vou perder|vamos perder|ja perdi|perdeu|perdi|derrota|eliminado)\b/],
 ['market',/\b(mercado|elenco|contratar|contratacao|comprar|vender|proposta|negociacao|reforco|transferencia|janela|contrato)\b/],
 ['tactics',/\b(formacao|tatica|marcacao|retranca|esquema|lateral|zagueiro)\b/],
 ['complaints',/\b(chorando|chorao|reclamando|roubado|desculpa|chorou|chora|roubo|juiz)\b/],
 ['victory',/\b(ganhou|ganhei|venceu|venci|vitoria)\b/],
 ['escape',/\b(fugir|fugiu|medo|arregou|sumiu|cade)\b/],
 ['tournament',/\b(campeao|campeonato|final|semifinal|semi|mata.mata|taca|copa)\b/],
 ['greeting',/^(oi|ola|opa|salve|bom dia|boa tarde|boa noite|e ai)[!?.\s]*$/]
 ];
 return rules.find(([,r])=>r.test(t))?.[0]??'general';
}
