// Approved draw pool. Existing Cup assignments remain stored with their Cup.
export const minicampClubs: readonly string[] = Object.freeze([
  'Arsenal', 'Manchester United', 'Barcelona', 'Atlético de Madrid', 'Bayern de Munique',
  'Borussia Dortmund', 'Bayer Leverkusen', 'Inter de Milão', 'AC Milan', 'Juventus',
  'Napoli', 'Roma', 'Lazio', 'Atalanta', 'Fiorentina', 'Bologna', 'Torino', 'Genoa',
  'Paris Saint-Germain', 'Monaco', 'Olympique de Marseille', 'Lyon', 'Lille', 'Lens',
  'Rennes', 'Nice', 'Palmeiras', 'Flamengo', 'São Paulo', 'Corinthians', 'Fluminense',
  'Botafogo', 'Vasco da Gama', 'Internacional', 'Grêmio', 'Atlético Mineiro', 'Cruzeiro',
  'Bahia', 'Fortaleza', 'Athletico Paranaense', 'Santos', 'Inter Miami', 'LA Galaxy',
  'Los Angeles FC', 'New York City FC', 'New York Red Bulls', 'Orlando City',
  'Seattle Sounders', 'Atlanta United', 'Al-Hilal', 'Al-Nassr', 'Al-Ittihad', 'Al-Ahli',
  'Al-Shabab', 'Ajax', 'PSV Eindhoven', 'Feyenoord', 'Benfica', 'Sporting CP', 'Porto',
  'Galatasaray', 'Fenerbahçe', 'Beşiktaş', 'Celtic', 'Rangers', 'Club América',
  'CD Guadalajara', 'Monterrey', 'Tigres UANL', 'Cruz Azul', 'Pumas UNAM',
  'Boca Juniors', 'River Plate', 'Racing Club', 'San Lorenzo', 'Colo-Colo',
  'Universidad de Chile', 'Atlético Nacional', 'Millonarios', 'América de Cali',
  'Barcelona de Guayaquil', 'LDU Quito', 'Peñarol', 'Nacional do Uruguai',
  'Shakhtar Donetsk', 'Dynamo Kyiv', 'Vissel Kobe', 'Yokohama F. Marinos',
  'Urawa Red Diamonds',
]);
